# Generated by Django 6.0.5 on 2026-05-16 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=3)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('blocked_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(db_index=True, max_length=20)),
                ('account_number', models.CharField(max_length=100)),
                ('available_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('blocked_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SSIInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterparty_bic', models.CharField(db_index=True, max_length=20)),
                ('safekeeping_account', models.CharField(max_length=100)),
                ('delivering_agent', models.CharField(blank=True, max_length=20, null=True)),
                ('receiving_agent', models.CharField(blank=True, max_length=20, null=True)),
                ('place_of_settlement', models.CharField(max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('isin', models.CharField(db_index=True, max_length=20)),
                ('security_name', models.CharField(max_length=255)),
                ('trade_date', models.DateField()),
                ('settlement_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('settlement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('counterparty_bic', models.CharField(max_length=20)),
                ('custody_account', models.CharField(blank=True, max_length=100, null=True)),
                ('cash_account', models.CharField(blank=True, max_length=100, null=True)),
                ('settlement_direction', models.CharField(choices=[('RECEIVE', 'Receive'), ('DELIVER', 'Deliver')], max_length=20)),
                ('payment_type', models.CharField(choices=[('FREE', 'Free of Payment'), ('AGAINST_PAYMENT', 'Against Payment')], max_length=30)),
                ('trade_status', models.CharField(choices=[('OPEN', 'Open'), ('SETTLED', 'Settled'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SWIFTMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('MT540', 'MT540 Receive Free'), ('MT541', 'MT541 Receive Against Payment'), ('MT542', 'MT542 Deliver Free'), ('MT543', 'MT543 Deliver Against Payment'), ('MT544', 'MT544 Receive Free Confirmation'), ('MT545', 'MT545 Receive Against Payment Confirmation'), ('MT546', 'MT546 Deliver Free Confirmation'), ('MT547', 'MT547 Deliver Against Payment Confirmation'), ('MT548', 'MT548 Settlement Status Advice')], max_length=10)),
                ('sender_bic', models.CharField(blank=True, max_length=20, null=True)),
                ('receiver_bic', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_ref', models.CharField(db_index=True, max_length=100)),
                ('related_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('function_code', models.CharField(blank=True, max_length=20, null=True)),
                ('trade_date', models.DateField(blank=True, null=True)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('preparation_date', models.DateField(blank=True, null=True)),
                ('isin', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('security_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('quantity_type', models.CharField(blank=True, max_length=20, null=True)),
                ('safekeeping_account', models.CharField(blank=True, max_length=100, null=True)),
                ('delivering_agent', models.CharField(blank=True, max_length=20, null=True)),
                ('receiving_agent', models.CharField(blank=True, max_length=20, null=True)),
                ('place_of_settlement', models.CharField(blank=True, max_length=20, null=True)),
                ('settlement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('settlement_direction', models.CharField(choices=[('RECEIVE', 'Receive'), ('DELIVER', 'Deliver'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('payment_type', models.CharField(choices=[('FREE', 'Free of Payment'), ('AGAINST_PAYMENT', 'Against Payment'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30)),
                ('settlement_status', models.CharField(blank=True, max_length=50, null=True)),
                ('matching_status', models.CharField(blank=True, max_length=50, null=True)),
                ('reason_code', models.CharField(blank=True, max_length=50, null=True)),
                ('narrative_reason', models.TextField(blank=True, null=True)),
                ('raw_message', models.TextField()),
                ('parsed_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swift_messages', to='uploads.uploadedswiftfile')),
            ],
        ),
    ]
