# Generated by Django 6.0.5 on 2026-05-17 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_cashbalance_securityholding_ssiinstruction_trade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_cause', models.CharField(max_length=255)),
                ('reason_category', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('investigation_status', models.CharField(default='COMPLETED', max_length=50)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('recommended_action', models.TextField(blank=True, null=True)),
                ('investigation_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('swift_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_result', to='uploads.swiftmessage')),
            ],
        ),
    ]
