# Generated by Django 6.0.5 on 2026-05-17 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_investigationresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrchestratedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE_JIRA_TICKET', 'Create Jira Ticket'), ('SEND_TEAMS_ALERT', 'Send Teams Alert'), ('SEND_EMAIL_ESCALATION', 'Send Email Escalation')], max_length=100)),
                ('target_system', models.CharField(choices=[('JIRA', 'Jira'), ('TEAMS', 'Microsoft Teams'), ('EMAIL', 'Email')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investigation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orchestrated_actions', to='uploads.investigationresult')),
            ],
        ),
    ]
