# Generated by Django 6.0.5 on 2026-05-17 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_orchestratedaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedswiftfile',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('parsed', 'Parsed'), ('duplicate', 'Duplicate'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('system', models.CharField(choices=[('UPLOAD', 'Upload Service'), ('AI_ENGINE', 'AI Engine'), ('ORCHESTRATOR', 'Action Orchestrator'), ('JIRA', 'Jira'), ('TEAMS', 'Microsoft Teams'), ('EMAIL', 'Email')], max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('INFO', 'Info')], default='SUCCESS', max_length=20)),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investigation_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='uploads.investigationresult')),
                ('orchestrated_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='uploads.orchestratedaction')),
                ('swift_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='uploads.swiftmessage')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['system'], name='uploads_aud_system_f4aafd_idx'), models.Index(fields=['status'], name='uploads_aud_status_8498a0_idx'), models.Index(fields=['created_at'], name='uploads_aud_created_fa92fb_idx')],
            },
        ),
    ]
